### ISSUE TITLE
Any chance of supporting arrays in translation files?

### ISSUE THREAD

**Issue by rvision** [DoneDeal0/Talkr#15]
Any chance of supporting arrays in translation files?

```
{
	"name": "English",
	"weekdays": ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
}

const weekdays = T('weekdays');
console.log(weekdays);        // returns null
```

**Comment by DoneDeal0** [comment]
Hi @rvision ,

Talkr is designed to render null and throw a warning if the output is not a string. Unfortunately, you can't render an array. However, if your goal is simply to display an array as a string, you may write `weekdays` like this:

```js
 "weekdays": "['Monday', 'Tuesday']"
```

**Comment by mcioffi** [comment]
@DoneDeal0 I would certainly upvote this if it were proposed as an enhancement on **Talkr** because the use cases might be pretty universal for folks, e.g. available on [ i18next here](https://www.i18next.com/translation-function/objects-and-arrays) and [next-translate here](https://github.com/aralroca/next-translate#7-nested-translations)

An explicit designation of some sort on the props could enforce the return of the array. 

i18next approaches it with `i18next.t('array', { returnObjects: true })`
next-translate, similarly, approaches it with `t('namespace:array-example', { count: 1 }, { returnObjects: true })`

**Comment by DoneDeal0** [comment]
Actually, it makes sense. I've made a pull request (#41) to handle this. I'll take advantage of it to bump the devDependencies, update the build process and the CI/CD. It should be available by the end of the week.

**Comment by mcioffi** [comment]
> Actually, it makes sense. I've made a pull request (#41) to handle this. I'll take advantage of it to bump the devDependencies, update the build process and the CI/CD. It should be available by the end of the week.

Thanks! 👍🏼 I believe this is the only line to be omitted. https://github.com/DoneDeal0/Talkr/blob/4040a3ba3916da8789009caedcb93878bac33014/src/tr.tsx#L47

**Comment by DoneDeal0** [comment]
Sorry, I pushed a bit too fast this morning. I can't believe I've made such a silly mistake. Anyways, it's fixed in [3.5.1](https://github.com/DoneDeal0/Talkr/releases/tag/v3.5.1).

**Comment by mcioffi** [comment]
All good, thank you for open-sourcing your work, especially like these to make tools and website more accessible to others around the 🌎

**Comment by DoneDeal0** [comment]
My pleasure, feel free to check out my other open source libs, like [Superdiff ](https://github.com/DoneDeal0/superdiff) or to [support](https://github.com/sponsors/DoneDeal0) their development if you use them professionally. Have a great day!
