### ISSUE TITLE
warning as an option

### ISSUE THREAD

**Issue by rejetto** [DoneDeal0/Talkr#32]
hi, I'm currently forced to disable the warning before calling T, and restoring every time, like this

        const bak = console.warn
        console.warn = () => {}

Could you make the warning optional, please?

If you wonder why i'm doing it, it's for 2 reasons
1) I'm applying a logic where different keys are attempted for the same text
2) I want a different warning message

**Comment by DoneDeal0** [comment]
Hi @rejetto ,

Thanks for your message! Someone already proposed to have an optional warning in #29 . 

In my opinion, the warning is necessary because you need to spot the missing translations in your app. I may be wrong but I don't think a `showWarning` prop would be a real added-value to the library. However, if your really want to remove `Talkr`'s warning, you can add the following code snippet at the root of your app (usually `index.(tsx|js)`):

```js
const consoleWarn = console.warn;
const SUPPRESSED_WARNINGS = ['Talkr: Missing translation'];

console.warn = function filterWarnings(msg, ...args) {
    if (!SUPPRESSED_WARNINGS.some((entry) => msg.includes(entry))) {
        consoleWarn(msg, ...args);
    }
};

```

> I'm applying a logic where different keys are attempted for the same text

I you have a conditionnal key like `T(modal.apply.${isPremium ? "close" : "buy"})`,  just add the two keys in your translation files. The warning is here for a good reason: spotting mistakes before sending your app into production.

If you need any help, please let me know.
