### ISSUE TITLE
detectBrowserLanguage is assigning not supported values

### ISSUE THREAD

**Issue by normandanielmq** [DoneDeal0/Talkr#37]
Hi! great library.

Just to let you know that when detectBrowserLanguage is used is assigns the browser's language even though is not included by the provided list of languages.

**Comment by DoneDeal0** [comment]
Hi @normandanielmq , thanks for your message! You're right, the function `initLocale()` might return an unsupported language when `detectBrowserLanguage` is activated. I'll correct that. However, there is no risk for existing users since the `T` function has a fallback to the default language (`const currentLocale = !languages[locale] ? defaultLanguage : locale;`)
