### ISSUE TITLE
Missing translations warning

### ISSUE THREAD

**Issue by rvision** [DoneDeal0/Talkr#4]
There should be some kind of handling missing translations. Either console.warn or something similar. This would be helpful to catch missing translations, especially if there are bunch of languages in the system and translators are translating independently.

Example:

console.log(t('hello12'));   // returns null

Btw, fantastic project, I've set it up and running in 15 minutes!

**Comment by DoneDeal0** [comment]
Hi Rvision,

Thanks for using Talkr, I'm glad you enjoyed it! Great suggestion. I've just implemented it. It should be available on npm very soon. Please note that t() has been updated to T() in v 2.0.0  because of a Typescript issue.

**Comment by rvision** [comment]
Fantastic 👍 

One more suggestion: placeholders are (to me) unintuitive in this format:

"simple": "You are __name__",

Can you consider maybe replacing it with something like we're already used in template literals?

"simple": "You are ${name}",

**Comment by DoneDeal0** [comment]
Unfortunately, I don't think I will implement such a change for the moment. I would need to change the parsing algorithm, and the computation wouldn't be as fast as it is now. But if I receive many requests like yours, I would of course consider to change it. 

Also, I've eventually let t() instead of T(). False alert. You responded so quickly, I didn't have time to edit my comment lol.

**Comment by rvision** [comment]
ok :)

I've find it better with T() instead of t() because it's easier to search (case sensitive)

**Comment by DoneDeal0** [comment]
Yes, I didn't thought about it, it might be very useful to navigate through translations. Alright, v2.1.0 will replace t() by T(). Npm is still unresponsive to the publication thought. The buggy version is still online.
